misalmeba="gamarjoba"
misalmeba2="gamarjoba"
saxeli="ra gqviat"
saxeli2="goga"
gvari="ra gvari xart"
gvari2="gorgadze"
simagle="ramdeni santimetria tqveni siagle"
simagle2="176.4"
weli="ramdeni wlis xart"
weli2="23"
dabadeba="romel wels daibadet"
dabadeba2="2000"
natesavi="gyavt da an dzma"
natesavi2="1 da da 2 dzma"
feri="tqveni sayvareli feri"
feri2="shavi"
manqana="romeli manqanebi mogwont"
manqana2="Toiota supra mk4,Doge celenger, Nissan GTR and Mersedes Benz Gelindvagn 6x6..."
sasmeli="sayvareli sasmeli"
sasmeli2="xilis wveni redbulis gemoti"
sawmeli="sayvareli sawmeli"
sawmeli2="xinkali"
lokacia="mtashi yofna barshi yofna tu zgvaze"
lokacia2="tashi mdinareze"

print(misalmeba + misalmeba2 + saxeli + saxeli2 + gvari + gvari2 + simagle + simagle2 + weli + weli2 + dabadeba +dabadeba2 + natesavi + natesavi2 + feri + feri2 + manqana + manqana2 + sasmeli +sasmeli2 + sawmeli + sawmeli2 + lokacia + lokacia2)